[workspace]
members = [
  "iroh",
  "iroh-bitswap",
  "iroh-car",
  "iroh-rpc-client",
  "iroh-rpc-types",
  "iroh-gateway",
  "iroh-metrics",
  "iroh-p2p",
  "iroh-resolver",
  "iroh-store",
  "iroh-util",
  "stores/*",
]

[patch.crates-io]
libp2p = { git = "https://github.com/dignifiedquire/rust-libp2p", rev = "dc5db669dae07680896e71cf0813c0154ca97918" }
# libp2p = { path = "../rust-libp2p" }
