[package]
name = "localops"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
dirs-next = "2.0.0"
handlebars = "4"
serde = { version = "1.0", features = ["derive"] }
which = "4.3.0"
sysinfo = "0.26.4"
users= "0.11.0"